
manual:
	make -C 2A03
	cp 2A03/build/manual.pdf 2A03.pdf
	make -C VRC6
	cp VRC6/build/manual.pdf VRC6.pdf
	make -C 106
	cp 106/build/manual.pdf 106.pdf
	make -C PotatoChips
	cp PotatoChips/build/manual.pdf PotatoChips.pdf
