
all: manual

build:
	mkdir -p build

mNameCorpOctalWaveGenerator: build
	make -C NameCorpOctalWaveGenerator
	cp NameCorpOctalWaveGenerator/build/manual.pdf build/NameCorpOctalWaveGenerator.pdf

mInfiniteStairs: build
	make -C InfiniteStairs
	cp InfiniteStairs/build/manual.pdf build/InfiniteStairs.pdf

mJairasullator: build
	make -C Jairasullator
	cp Jairasullator/build/manual.pdf build/Jairasullator.pdf

mBossFight: build
	make -C BossFight
	cp BossFight/build/manual.pdf build/BossFight.pdf

mMiniBoss: build
	make -C MiniBoss
	cp MiniBoss/build/manual.pdf build/MiniBoss.pdf

mPulses: build
	make -C Pulses
	cp Pulses/build/manual.pdf build/Pulses.pdf

mPalletTownWavesSystem: build
	make -C PalletTownWavesSystem
	cp PalletTownWavesSystem/build/manual.pdf build/PalletTownWavesSystem.pdf

mMegaTone: build
	make -C MegaTone
	cp MegaTone/build/manual.pdf build/MegaTone.pdf

mPotKeys: build
	make -C PotKeys
	cp PotKeys/build/manual.pdf build/PotKeys.pdf

mStepSaw: build
	make -C StepSaw
	cp StepSaw/build/manual.pdf build/StepSaw.pdf

mSuperEcho: build
	make -C SuperEcho
	cp SuperEcho/build/manual.pdf build/SuperEcho.pdf

mSuperVCA: build
	make -C SuperVCA
	cp SuperVCA/build/manual.pdf build/SuperVCA.pdf

mSuperADSR: build
	make -C SuperADSR
	cp SuperADSR/build/manual.pdf build/SuperADSR.pdf

manual: mNameCorpOctalWaveGenerator mInfiniteStairs mJairasullator mBossFight mMiniBoss mPulses mPalletTownWavesSystem mMegaTone mPotKeys mStepSaw mSuperEcho mSuperVCA mSuperADSR
